name : Deploy Static Site 2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check FTP credentials
        run: |
          if [ -z "$FTP_USER" ]; then
            echo "FTP_USERNAME is EMPTY"
          else
            echo "FTP_USERNAME is available"
          fi
        env:
          FTP_USER: ${{ secrets.FTP_USERNAME }}
        
      - name: Deploy to GoDaddy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: 12.218.12.198.host.secureserver.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /

